name: Remote Dispatch Playwright Tests

on:
  workflow_dispatch:
    inputs:
      app-name:
        type: choice
        required: true
        description: Which app to run tests for
        options:
        - mac
      repository:
        type: string
        required: true
        description: The repository to run tests for (e.g., user/repo)
      sha:
        type: string
        default: main
        description: The commit SHA to run tests for
      environment:
        type: choice
        description: The environment to run tests in
        options:
          - dev
          - mac-dev
          - prod
          - mac-prod
        default: prod

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send Init Message
      if: ${{ github.event.inputs.app-name == 'macos' }}
      run: echo "Hello, macOS! Running tests for commit ${{ github.event.inputs.sha }} in environment ${{ github.event.inputs.environment }}."

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Root Repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # Attempt to restore pnpm cache to speed up dependency installation
      - name: Restore pnpm cache (if any)
        id: pnpm_cache
        uses: actions/cache@v5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        shell: bash
        if: steps.pnpm_cache.outputs.cache-hit != 'true'
        run: |
          pnpm install
          echo "Saving pnpm cache... ${{ steps.pnpm_cache.outputs.cache-primary-key || 'no-key' }}"

      - name: Save pnpm cache (if changed)
        uses: actions/cache@v5
        if: steps.pnpm_cache.outputs.cache-hit != 'true'
        with:
          path: |
            node_modules
          key: ${{ steps.pnpm_cache.outputs.cache-primary-key }}
        continue-on-error: true

      # Setup Playwright and dependencies in the root repository
      # TODO: Cache Playwright browsers to speed up test runs
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      # Checkout the code of the target repository and run tests
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.sha }}
          path: app
      - name: List app directory
        run: ls app
      - name: Install Repository Dependencies
        working-directory: ./app
        run: pnpm install
      # Initialize Test Environment Variables and Run Playwright tests
      - name: Run Playwright tests
        run:  TEST_ENV=${{ github.event.inputs.environment }} npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30