name: Remote Dispatch Playwright Tests

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
        description: The repository to checkout (e.g., user/repo)
      sha:
        type: string
        default: main
        description: The commit SHA to checkout (e.g., main, a specific branch, or a commit hash)
      environment:
        type: string
        required: true
        description: The environment to run tests in (e.g., prod | *-prod | mac-dev | *-dev)

jobs:
  Log-Init-Message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Log
      run: echo "Running tests for commit ${{ github.event.inputs.sha }} in environment ${{ github.event.inputs.environment }} from ${{ github.event.inputs.repository }}."
    - name: Send Log of Root Repository
      run: echo "Running tests from ${{ github.repository }} commit ${{ github.sha }}."
  Dispatch-Playwright-Tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Root Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # Attempt to restore pnpm cache to speed up dependency installation
      - name: Restore pnpm cache (if any)
        id: pnpm_cache
        uses: actions/cache@v5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        shell: bash
        if: steps.pnpm_cache.outputs.cache-hit != 'true'
        run: |
          pnpm install
          echo "Saving pnpm cache... ${{ steps.pnpm_cache.outputs.cache-primary-key || 'no-key' }}"

      - name: Save pnpm cache (if changed)
        uses: actions/cache@v5
        if: steps.pnpm_cache.outputs.cache-hit != 'true'
        with:
          path: |
            node_modules
          key: ${{ steps.pnpm_cache.outputs.cache-primary-key }}
        continue-on-error: true
      # Setup Playwright and dependencies in the root repository
      # TODO: Cache Playwright browsers to speed up test runs
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # Checkout the code of the target repository and run tests
      - name: Checkout code
        if: ${{ github.event.inputs.environment != 'prod' }}
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.inputs.repository || github.repository }}
          ref: ${{ github.event.inputs.sha || github.sha }}
          path: app
      - name: List app directory
        if: ${{ github.event.inputs.environment != 'prod' }}
        run: ls app
      - name: Install Repository Dependencies
        if: ${{ github.event.inputs.environment != 'prod' }}
        working-directory: ./app
        run: pnpm install
      # Initialize Test Environment Variables and Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
